removed weird character in tr_status
this was making Rmd website crash with this error:

```
pandoc: Cannot decode byte '\xd2': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream
Error: pandoc document conversion failed with error 1
In addition: There were 21 warnings (use warnings() to see them)
Execution halted
```

Because it looked like this: 
>Status scores calculated based on [�Study on Blue Growth, Maritime Policy and the EU Strategy for the Baltic Sea Region�](https://webgate.ec.europa.eu/maritimeforum/node/3550)